import { Layout } from '@/components/Layout';
import { Link } from 'wouter';
import { motion } from 'framer-motion';

export default function Terms() {
  const sections = [
    {
      title: "1. Acceptance of Terms",
      content: (
        <p className="mb-4">
          By installing or using the Reedr browser extension ("Reedr" or "the Extension"), you agree to be bound by these Terms of Use. If you do not agree, please uninstall the Extension and do not use it. These Terms apply to all users of Reedr.
        </p>
      )
    },
    {
      title: "2. Who Can Use Reedr",
      content: (
        <>
          <p className="mb-4">
            Reedr is intended for users aged <strong>13 and older</strong>. By installing the Extension, you represent that you are at least 13 years of age. If you are under 18, you represent that your parent or legal guardian has reviewed and agreed to these Terms on your behalf.
          </p>
          <p className="mb-4">
            Reedr is a reading and research tool. It reads web pages and PDFs alongside you and answers your questions about them. It is not a substitute for professional advice of any kind.
          </p>
        </>
      )
    },
    {
      title: "3. Nature of the Service",
      content: (
        <>
          <p className="mb-4">Reedr is an AI-powered browser companion. You should be aware of the following:</p>
          <ul className="list-disc pl-6 space-y-3 mb-4">
            <li>
              <strong>Reedr is an AI, not a person.</strong> Responses are generated by artificial intelligence and may be inaccurate, incomplete, or out of date.
            </li>
            <li>
              <strong>Responses may be wrong.</strong> Reedr can misread, misinterpret, or miss content on a page. Do not rely solely on Reedr for important decisions — always read the source material yourself.
            </li>
            <li>
              <strong>Not a substitute for professional advice.</strong> Nothing Reedr says constitutes legal, medical, financial, or any other professional advice. If you need professional guidance, consult a qualified professional.
            </li>
            <li>
              <strong>Page content varies.</strong> Reedr reads what is visible on a page at the time you open the chat. Dynamic content, paywalled content, or content that loads after scroll may not be captured.
            </li>
          </ul>
        </>
      )
    },
    {
      title: "4. Permitted Use",
      content: (
        <>
          <p className="mb-4">You may use Reedr for personal, non-commercial browsing assistance. You agree not to:</p>
          <ul className="list-disc pl-6 space-y-3 mb-4">
            <li>Use the Extension to generate or distribute harmful, illegal, or abusive content.</li>
            <li>Attempt to manipulate Reedr into producing content that violates these Terms or applicable law.</li>
            <li>Reverse-engineer, decompile, or attempt to extract the underlying AI models or extension source beyond what is provided.</li>
            <li>Use the Extension in any way that violates applicable laws or regulations, or infringes any third party's rights.</li>
            <li>Use automated systems to send large volumes of messages to Reedr in a manner that disrupts service for others.</li>
          </ul>
        </>
      )
    },
    {
      title: "5. Your Content",
      content: (
        <>
          <p className="mb-4">
            You retain ownership of any messages you send to Reedr. By sending them, you grant us a limited licence to process that content solely to generate Reedr's responses. We do not store your messages on our servers beyond the duration of the API call needed to produce a reply.
          </p>
          <p className="mb-4">
            You are responsible for the content you submit. Do not share sensitive personal information, passwords, or confidential data belonging to others through the chat.
          </p>
        </>
      )
    },
    {
      title: "6. Third-Party Content",
      content: (
        <p className="mb-4">
          Reedr reads and discusses content from third-party websites and documents. We do not own, control, or endorse that content. Reedr's discussion of a page is not an endorsement of its accuracy, legality, or quality. You are responsible for evaluating the credibility of sources you read.
        </p>
      )
    },
    {
      title: "7. Privacy",
      content: (
        <p className="mb-4">
          Our collection and use of your data is described in our{' '}
          <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>,
          which is incorporated into these Terms by reference. By using Reedr, you consent to the data practices described there. Key points: your conversation history is stored only on your own device, and we collect no personal information.
        </p>
      )
    },
    {
      title: "8. Intellectual Property",
      content: (
        <p className="mb-4">
          The Reedr Extension — including its design, code, branding, and underlying technology — is owned by us and protected by intellectual property law. You may not copy, reproduce, distribute, or create derivative works from any part of Reedr without our prior written permission. Reading and discussing third-party web content through Reedr does not grant you any rights to that content beyond what applies under copyright law generally.
        </p>
      )
    },
    {
      title: "9. Disclaimers",
      content: (
        <>
          <p className="mb-4">
            Reedr is provided "as is" and "as available" without warranties of any kind. We do not warrant that:
          </p>
          <ul className="list-disc pl-6 space-y-2 mb-4">
            <li>The Extension will work on every website or browser version.</li>
            <li>Reedr's responses will be accurate, complete, or appropriate for your situation.</li>
            <li>The Extension will be uninterrupted or error-free.</li>
          </ul>
          <p>
            To the fullest extent permitted by law, we disclaim all warranties, including implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
          </p>
        </>
      )
    },
    {
      title: "10. Limitation of Liability",
      content: (
        <p className="mb-4">
          To the fullest extent permitted by applicable law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of Reedr — including any reliance on Reedr's responses, decisions made based on information Reedr provided, or inability to access the Extension. Our total liability for any claim shall not exceed the amount you paid for the Extension in the preceding 12 months (which for a free extension is zero).
        </p>
      )
    },
    {
      title: "11. Changes to the Extension and Terms",
      content: (
        <p className="mb-4">
          We may update Reedr or these Terms at any time. When we update the Terms, we will revise the "Last updated" date below. We may also notify users through the Extension or our website. Continued use of Reedr after any changes constitutes acceptance of the updated Terms.
        </p>
      )
    },
    {
      title: "12. Governing Law",
      content: (
        <p className="mb-4">
          These Terms are governed by applicable law. Any disputes arising from your use of Reedr shall first be addressed through good-faith negotiation. Nothing in these Terms limits any rights you may have under the mandatory consumer protection laws of your jurisdiction.
        </p>
      )
    },
    {
      title: "13. Contact",
      content: (
        <p className="mb-4">
          Questions about these Terms?{' '}
          <a href="mailto:support@victor.ai.life" className="text-primary hover:underline">support@victor.ai.life</a>
        </p>
      )
    }
  ];

  return (
    <Layout>
      <div className="pt-32 pb-20 px-6 md:px-12 max-w-4xl mx-auto w-full">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <Link href="/" className="text-primary hover:text-foreground transition-colors text-sm tracking-widest uppercase font-semibold flex items-center gap-2 mb-8">
            <span className="text-lg leading-none">&larr;</span> Back to Home
          </Link>

          <h1 className="text-4xl md:text-6xl font-serif mb-6">Terms of Use</h1>
          <p className="text-muted-foreground tracking-wide text-sm mb-16 uppercase">
            Last updated: July 21, 2026
          </p>

          <div className="prose prose-lg prose-headings:font-serif prose-headings:font-normal prose-headings:text-foreground prose-p:text-secondary/80 prose-li:text-secondary/80 max-w-none">
            <p className="text-xl font-serif italic text-secondary border-l-2 border-primary pl-6 mb-12">
              Reedr is a browser extension. He reads web pages with you. These terms explain what that means and what you can expect from us.
            </p>

            <div className="space-y-12">
              {sections.map((section, index) => (
                <motion.section
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: index * 0.04 }}
                >
                  <h2 className="text-2xl md:text-3xl font-serif mb-6">{section.title}</h2>
                  <div className="text-lg leading-relaxed font-sans">
                    {section.content}
                  </div>
                </motion.section>
              ))}
            </div>
          </div>
        </motion.div>
      </div>
    </Layout>
  );
}
