import { Layout } from '@/components/Layout';
import { Link } from 'wouter';
import { motion } from 'framer-motion';

export default function Terms() {
  const sections = [
    {
      title: "1. Acceptance of Terms",
      content: (
        <p className="mb-4">
          By downloading, installing, or using Victor ("the App"), you agree to be bound by these Terms of Use. If you do not agree, do not use the App. These Terms apply to all users of Victor.
        </p>
      )
    },
    {
      title: "2. Who Can Use Victor",
      content: (
        <>
          <p className="mb-4">
            Victor is intended for users aged <strong>13 and older</strong>. By using the App, you represent that you are at least 13 years of age. If you are under 18, you represent that your parent or legal guardian has reviewed and agreed to these Terms on your behalf.
          </p>
          <p className="mb-4">
            Victor is designed as an AI companion for conversation, reflection, and everyday practical help. It is not a substitute for professional mental health care, medical advice, crisis services, or human relationships.
          </p>
        </>
      )
    },
    {
      title: "3. Nature of the Service",
      content: (
        <>
          <p className="mb-4">Victor is an AI-powered conversational companion. You should be aware of the following:</p>
          <ul className="list-disc pl-6 space-y-3 mb-4">
            <li>
              <strong>Victor is an AI, not a person.</strong> Responses are generated by artificial intelligence and may be inaccurate, incomplete, or inappropriate for your specific situation.
            </li>
            <li>
              <strong>Not a substitute for professional help.</strong> Victor is not a licensed therapist, counsellor, doctor, lawyer, financial adviser, or any other professional. Nothing Victor says constitutes professional advice. If you are in crisis or need professional support, please contact a qualified professional or emergency services.
            </li>
            <li>
              <strong>Not a crisis service.</strong> If you are experiencing a mental health emergency, please contact emergency services (e.g. 911 in the US) or a crisis line (e.g. 988 Suicide & Crisis Lifeline in the US).
            </li>
            <li>
              <strong>Responses may be inaccurate.</strong> Victor may generate incorrect information. Do not rely solely on Victor for important decisions.
            </li>
          </ul>
        </>
      )
    },
    {
      title: "4. Permitted Use",
      content: (
        <>
          <p className="mb-4">You may use Victor for personal, non-commercial conversation and companionship. You agree not to:</p>
          <ul className="list-disc pl-6 space-y-3 mb-4">
            <li>Use the App to generate or distribute harmful, illegal, or abusive content.</li>
            <li>Attempt to manipulate Victor into producing content that violates these Terms or applicable law.</li>
            <li>Use the App in any way that could harm other people.</li>
            <li>Attempt to reverse-engineer, decompile, or extract the underlying AI models or software.</li>
            <li>Use the App for any unlawful purpose or in violation of any applicable laws or regulations.</li>
          </ul>
        </>
      )
    },
    {
      title: "5. Your Content",
      content: (
        <>
          <p className="mb-4">
            You retain ownership of any content you submit to Victor. By submitting content, you grant us a limited licence to process that content solely for the purpose of providing Victor's responses to you.
          </p>
          <p className="mb-4">
            You are responsible for ensuring that any content you submit does not infringe the rights of others and complies with applicable law. Do not submit sensitive personal information about third parties without their consent.
          </p>
        </>
      )
    },
    {
      title: "6. Privacy",
      content: (
        <p className="mb-4">
          Our collection and use of your data is described in our{' '}
          <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>,
          which is incorporated into these Terms by reference. By using Victor, you consent to the data practices described in the Privacy Policy.
        </p>
      )
    },
    {
      title: "7. Intellectual Property",
      content: (
        <p className="mb-4">
          The Victor app, including its design, software, branding, and underlying technology, is owned by us and protected by intellectual property laws. You may not copy, reproduce, distribute, or create derivative works from any part of Victor without our prior written permission.
        </p>
      )
    },
    {
      title: "8. Disclaimers",
      content: (
        <>
          <p className="mb-4">
            Victor is provided "as is" and "as available" without warranties of any kind, express or implied. We do not warrant that:
          </p>
          <ul className="list-disc pl-6 space-y-2 mb-4">
            <li>The App will be uninterrupted, error-free, or secure.</li>
            <li>Victor's responses will be accurate, complete, or appropriate for your situation.</li>
            <li>The App will meet your specific requirements.</li>
          </ul>
          <p className="mb-4">
            To the fullest extent permitted by law, we disclaim all warranties, including implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
          </p>
        </>
      )
    },
    {
      title: "9. Limitation of Liability",
      content: (
        <p className="mb-4">
          To the fullest extent permitted by applicable law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of Victor, including but not limited to reliance on Victor's responses, loss of data, or inability to access the App. Our total liability for any claim arising from your use of Victor shall not exceed the amount you paid for the App in the 12 months preceding the claim (which for a free app is zero).
        </p>
      )
    },
    {
      title: "10. Changes to the App and Terms",
      content: (
        <p className="mb-4">
          We reserve the right to modify or discontinue Victor, or to update these Terms, at any time. When we update the Terms, we will revise the "Last updated" date. Continued use of Victor after any changes constitutes your acceptance of the updated Terms.
        </p>
      )
    },
    {
      title: "11. Governing Law",
      content: (
        <p className="mb-4">
          These Terms are governed by and construed in accordance with applicable law. Any disputes arising from your use of Victor shall be resolved through good-faith negotiation where possible.
        </p>
      )
    },
    {
      title: "12. Contact",
      content: (
        <p className="mb-4">
          For questions about these Terms, please contact us at{' '}
          <a href="mailto:support@victor.ai.life" className="text-primary hover:underline">support@victor.ai.life</a>.
        </p>
      )
    }
  ];

  return (
    <Layout>
      <div className="pt-32 pb-20 px-6 md:px-12 max-w-4xl mx-auto w-full">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <Link href="/" className="text-primary hover:text-foreground transition-colors text-sm tracking-widest uppercase font-semibold flex items-center gap-2 mb-8">
            <span className="text-lg leading-none">&larr;</span> Back to Home
          </Link>
          
          <h1 className="text-4xl md:text-6xl font-serif mb-6">Terms of Use</h1>
          <p className="text-muted-foreground tracking-wide text-sm mb-16 uppercase">
            Last updated: July 2026
          </p>

          <div className="prose prose-lg prose-headings:font-serif prose-headings:font-normal prose-headings:text-foreground prose-p:text-secondary/80 prose-li:text-secondary/80 max-w-none">
            <p className="text-xl font-serif italic text-secondary border-l-2 border-primary pl-6 mb-12">
              Please read these terms carefully. They explain what Victor is, what it isn't, and how you can use it.
            </p>

            <div className="space-y-12">
              {sections.map((section, index) => (
                <motion.section 
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: index * 0.05 }}
                >
                  <h2 className="text-2xl md:text-3xl font-serif mb-6">{section.title}</h2>
                  <div className="text-lg leading-relaxed font-sans">
                    {section.content}
                  </div>
                </motion.section>
              ))}
            </div>
          </div>
        </motion.div>
      </div>
    </Layout>
  );
}
